stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy-job:
  stage: deploy
  image: node:18
  script:
    - npm install -g netlify-cli
    - netlify deploy --prod --dir=dist/ --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  only:
    - main

deploy-vercel:
  stage: deploy
  image: node:18
  script:
    - npm install -g vercel
    - vercel pull --yes --token $VERCEL_TOKEN --org-id $VERCEL_ORG_ID --project-id $VERCEL_PROJECT_ID
    - vercel build --token $VERCEL_TOKEN
    - vercel deploy --prod --token $VERCEL_TOKEN
  only:
    - main
