stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  image: node:18
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy-netlify:
  stage: deploy
  image: node:18
  script:
    - npm install -g netlify-cli
    - netlify deploy --prod --dir=dist/
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success

deploy-vercel:
  stage: deploy
  image: node:18
  script:
    - npm install -g vercel
    - vercel deploy --prod --token $VERCEL_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
